name: Flutter Build & Release

on:
  push:
    branches:
      - lab1 # يعمل فقط عند الرفع على هذا الفرع

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. جلب الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. إعداد بيئة الجافا (مطلوبة للأندرويد)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. تثبيت Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. جلب المكاتب
      - name: Install Dependencies
        run: flutter pub get

      # 5. بناء ملف APK
      - name: Build APK
        run: flutter build apk --release

      # 6. إنشاء الـ Release ورفع الملف
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          # يقوم بعمل تاج تلقائي برقم العملية (مثلاً v1.0.5)
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets._GITHUB_TOKEN }} # التوكن الذي قمت أنت بإنشائه
